### ISSUE TITLE
White Screen for google map

### ISSUE THREAD

**Issue by VishnuPrabhu** [dhaval0122/DJ-Android-#2]
The Problem is We have to change the package name and create new api key, then only it works else it always shows empty white screen for google map

**Comment by dhaval0122** [comment]
that's true, 

Google Map v2 we have to generate MAP API key with package and KEYSTORE SHA1, so its different for every one(in my case i already use my package so Google not allow to use same package name)

check documentation https://developers.google.com/maps/documentation/android/start
